import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import ThemeState from '@/context/ThemeState'
import Navbar from '@/components/navbar/Navbar'
import ThemeButton from '@/components/theme/ThemeButton'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: 'white' },
    { media: '(prefers-color-scheme: dark)', color: 'black' },
  ],
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={cn(inter.className)}>
        <ThemeState>
          <Navbar />
          {children}

          <ThemeButton />
        </ThemeState>
      </body>
    </html>
  )
}
